name: Python Pipeline

on: [push]

jobs:
  python-pipeline:
    runs-on: [ubuntu-latest]
    name: Django Project 2
    steps:
    - name: checkout source repo
      uses: actions/checkout@v2
      
    - name: List folder content
      run: |
        ls -l
        
    - name: Setting up the python environment
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        pip install pytest

    - name: Lint with flake8
      run: |
        flake8 --ignore=E128,E402,E501 --exklude=v_env
        
